require './vagrant-provision-reboot-plugin'

Vagrant.configure(2) do |config|

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "rifung/win7_32"
  config.vm.guest = :windows
  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |vb|
    vb.name = "Chowan-sgandhi4-UOST"
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
  
    # Customize the amount of memory on the VM:
    vb.memory = "1024"
  end

  config.vm.communicator = "winrm"

  config.vm.provision :shell, path: "ShellScript/install_chocolatey.bat"
  config.vm.provision :shell, path: "ShellScript/install_softwares.bat"   
  config.vm.provision :windows_reboot
  config.vm.provision :shell, path: "ShellScript/install_tool.bat"
  config.vm.provision :windows_reboot
  config.vm.provision :shell, path: "ShellScript/complete_installations.bat"
  config.vm.provision :windows_reboot

end
